ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
  - tsx@4.22.3
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - example
onlyBuiltDependencies:
  - esbuild
  - sharp
allowBuilds:
  esbuild: true
  sharp: true
